### ISSUE TITLE
Couldn't create library openaas

### ISSUE THREAD

**Issue by Joy2233** [acplt/openAAS#2]
We followed the instruction to add “LIBRARY openaas” in ov_server.conf. But error shown as "[ACPLT/OV Error] Could'nt create library openaas: unknown class definition (error code 0x10028)]” when starting ACPLT/RTE server (acplt\servers\MANAGER\build_database.bat, acplt\servers\MANAGER\start_server.bat). Besides, I am not able to browse files on the server through uaExpert. Could you please give us more detail instructions on this? We will appreciate it.

**Comment by FlorianPalm** [comment]
Hello,
we have updated the instructions. Hopefully, you will be able to start the without an errror. Please have a try.

**Comment by Joy2233** [comment]
Thank you for your super quick response. It worked!

**Comment by FlorianPalm** [comment]
Nice to hear, you're welcome.
