### ISSUE TITLE
Workshop image -  link not valid

### ISSUE THREAD

**Issue by jwende** [acplt/openAAS#6]
If I click on the link for the workshp image a RWTH page opens - but the message is: 'link not valid'

**Comment by FlorianPalm** [comment]
Sorry for this, the link has expired. I have updated it. Please have another try.

**Comment by jwende** [comment]
works now - thank you

**Comment by fknietzsch** [comment]
Is the link down again? I wanted to try out the image but the following is displayed:
![image](https://user-images.githubusercontent.com/18595468/36642970-342f10ec-1a46-11e8-8359-330336cede04.png)
I hope this can be fixed.
Thanks a lot in advance!

**Comment by nikhilbchilwant** [comment]
Please upload image to something like Google Drive/Dropbox.
